const proffys = [
    {
        name: "Francisco Guedes",
        avatar: "https://avatars2.githubusercontent.com/u/2254731?s=460&u=0ba16a79456c2f250e7579cb388fa18c5c2d7d65&v=4",
        whatsapp: "73988954520",
        bio: "Gosto de hackear",
        subject: "Física",
        cost: "1999",
        weekday: [0],
        time_from: [720],
        time_to: [1220]
    },
    {
        name: "joão cleber",
        avatar: "https://avatars2.githubusercontent.com/u/2254731?s=460&u=0ba16a79456c2f250e7579cb388fa18c5c2d7d65&v=4",
        whatsapp: "73988954520",
        bio: "Gosto de hackear",
        subject: "Física",
        cost: "1999",
        weekday: [0],
        time_from: [720],
        time_to: [1220]
    },
    {
        name: "cleiton rasta",
        avatar: "https://avatars2.githubusercontent.com/u/2254731?s=460&u=0ba16a79456c2f250e7579cb388fa18c5c2d7d65&v=4",
        whatsapp: "73988954520",
        bio: "Gosto de hackear",
        subject: "Física",
        cost: "1999",
        weekday: [0],
        time_from: [720],
        time_to: [1220]
    }
]